import crypto from 'crypto';

const ALGORITHM = 'aes-256-gcm';

// We evaluate this at module load. If the key is missing or the wrong size,
// it fails loudly during build or server startup, which is what we want.
const getEncryptionKey = (): Buffer => {
  const keyStr = process.env.ENCRYPTION_KEY;
  if (!keyStr) {
    throw new Error('ENCRYPTION_KEY environment variable is not set. It must be a 32-byte base64-encoded string.');
  }

  const key = Buffer.from(keyStr, 'base64');
  if (key.length !== 32) {
    throw new Error(`ENCRYPTION_KEY must decode to exactly 32 bytes (got ${key.length} bytes).`);
  }

  return key;
};

/**
 * Encrypts a plaintext string using AES-256-GCM.
 * @param plaintext The sensitive data to encrypt.
 * @returns A composite string in the format "iv:authTag:ciphertext" (all base64).
 */
export function encrypt(plaintext: string): string {
  const key = getEncryptionKey();
  const iv = crypto.randomBytes(12); // Standard IV length for GCM
  
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let ciphertext = cipher.update(plaintext, 'utf8', 'base64');
  ciphertext += cipher.final('base64');
  
  const authTag = cipher.getAuthTag().toString('base64');
  
  return `${iv.toString('base64')}:${authTag}:${ciphertext}`;
}

/**
 * Decrypts a payload previously generated by `encrypt`.
 * @param payload The composite string in the format "iv:authTag:ciphertext".
 * @returns The original plaintext.
 */
export function decrypt(payload: string): string {
  const key = getEncryptionKey();
  const parts = payload.split(':');
  
  if (parts.length !== 3) {
    throw new Error('Invalid encrypted payload format. Expected "iv:authTag:ciphertext".');
  }
  
  const [ivBase64, authTagBase64, ciphertextBase64] = parts;
  
  const iv = Buffer.from(ivBase64, 'base64');
  const authTag = Buffer.from(authTagBase64, 'base64');
  
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  
  let plaintext = decipher.update(ciphertextBase64, 'base64', 'utf8');
  plaintext += decipher.final('utf8');
  
  return plaintext;
}

/**
 * Masks an API key for safe display in the UI (e.g. "sk-ant-...wxyz").
 * Shows the first 7 characters (to keep the provider prefix like "sk-ant-")
 * and the last 4 characters.
 */
export function maskKey(rawKey: string): string {
  if (!rawKey || rawKey.length <= 11) {
    return '***';
  }
  
  const prefix = rawKey.substring(0, 7);
  const suffix = rawKey.substring(rawKey.length - 4);
  
  return `${prefix}...${suffix}`;
}
